### ISSUE TITLE
Can you please provide source code of scrapbookqmsg?

### ISSUE THREAD

**Issue by victorfence** [tahama/scrapbookq#18]
I'm under Archlinux, My scrapbookq's not working now, it was.

This maybe the reason:
The request of file fails:
curl http://localhost:33338/scrapbook0/rdf/scrapbookq.rdf
404 page not found

For me, the best way is to read code of the http server scrapbookqmsg, to know what's going wrong.

Thanks.

**Comment by pnayyer** [comment]
Sorry, I found the source code.
Now I meet new issue,  it seems request success, but firefox popup a dialog which shows:

Native application tried to send a message of 1633771873 bytes, which exceeds the limit of 1048576 bytes.

And scrapbookq still do not work.
